name: ServerEconomy
version: '${project.version}'
main: me.conormcdr.servereconomy.servereconomy
api-version: 1.19
authors: [ Conormcdr ]
description: A simple economy plugin
commands:
  balance:
    description: Gets the players current balance.
    usage: /balance
    permission: seconomy.balance
    aliases: bal
  pay:
    description: Pay another player from your balance.
    usage: /pay <Player> <Amount>
    permission: seconomy.pay
  addfunds:
    description: Adds funds to a players balance without taking any from the sender.
    usage: /addfunds <Player> <Amount>
    permission: seconomy.addfunds
  setfunds:
    description: Sets the funds of a players balance to the amount specified.
    usage: /setfunds <Player> <Amount>
    permission: seconomy.setfunds
  grandexchange:
    description: Opens the hub for player sold items
    usage: /grandexchange
    permission: seconomy.ge
    aliases: ge
  sellhand:
    description: Adds the items in hand to the Grand Exchange for 7 days.
    usage: /sellhand <Amount>
    permission: seconomy.geadd
    aliases: sh
  leaderboard:
    description: Shows the server's top earners.
    usage: /leaderboard
    permission: seconomy.leaderboard
    aliases: lb
  exchange:
    description: Opens the hub for exchanging your items for currency.
    usage: /grandexchange
    permission: seconomy.exchange
    aliases: ex
permissions:
  seconomy.balance:
    description: none
    default: true
  seconomy.pay:
    description: none
    default: true
  seconomy.addfunds:
    description: none
    default: false
  seconomy.setfunds:
    description: none
    default: false
  seconomy.ge:
    description: none
    default: true
  seconomy.geadd:
    description: none
    default: true
  seconomy.leaderboard:
    description: none
    default: true
  seconomy.exchange:
    description: none
    default: true